# actions/gantry_calibration.yaml
# Hot-loadable action for calibrating the camera gantry (pan/tilt)
# Hardware config (ports, IDs, limits) comes from config.hardware.HardwareConfig
name: gantry_calibration
version: "1.0"
description: "Calibrate the 2-DOF camera gantry (Feetech pan/tilt)"
category: calibration

parameters:
  mode:
    type: string
    enum: [full, pan_only, tilt_only, center]
    default: full
    description: "Which servos to calibrate"
  speed:
    type: number
    minimum: 0.1
    maximum: 1.0
    default: 0.3
    description: "Movement speed during calibration"

# Calibration sequence - verbal command driven
execution:
  type: calibration_sequence
  subsystem: gantry
  cli_tool: solo

  steps:
    - name: center_gantry
      action: move_to_position
      params:
        pan: 0
        tilt: 0
        speed: "{{speed}}"
      speak: "Centering the camera gantry"
      await_confirmation: false

    - name: test_pan_left
      condition: "{{mode}} in ['full', 'pan_only']"
      action: move_to_position
      params:
        pan: -90
        tilt: 0
        speed: "{{speed}}"
      speak: "Panning left. Can you see the camera move?"
      await_confirmation: true

    - name: test_pan_right
      condition: "{{mode}} in ['full', 'pan_only']"
      action: move_to_position
      params:
        pan: 90
        tilt: 0
        speed: "{{speed}}"
      speak: "Panning right"
      await_confirmation: true

    - name: center_pan
      condition: "{{mode}} in ['full', 'pan_only']"
      action: move_to_position
      params:
        pan: 0
        tilt: 0
        speed: "{{speed}}"
      speak: "Centering pan"
      await_confirmation: false

    - name: test_tilt_up
      condition: "{{mode}} in ['full', 'tilt_only']"
      action: move_to_position
      params:
        pan: 0
        tilt: -45
        speed: "{{speed}}"
      speak: "Tilting up"
      await_confirmation: true

    - name: test_tilt_down
      condition: "{{mode}} in ['full', 'tilt_only']"
      action: move_to_position
      params:
        pan: 0
        tilt: 45
        speed: "{{speed}}"
      speak: "Tilting down"
      await_confirmation: true

    - name: center_tilt
      condition: "{{mode}} in ['full', 'tilt_only']"
      action: move_to_position
      params:
        pan: 0
        tilt: 0
        speed: "{{speed}}"
      speak: "Centering tilt. Gantry calibration complete."
      await_confirmation: false

# Verbal triggers
triggers:
  - pattern: "calibrate.*camera|calibrate.*gantry|test.*pan.*tilt"
    action: gantry_calibration
    params:
      mode: full

  - pattern: "center.*camera|home.*gantry"
    action: gantry_calibration
    params:
      mode: center
