# actions/gantry_calibration.yaml
# Hot-loadable calibration for Feetech pan/tilt servos on OAK-D Pro gantry
name: gantry_calibration
version: "1.0"
description: "Calibrate the 2-DOF camera gantry (Feetech pan/tilt servos)"
category: calibration

# Hardware configuration
hardware:
  bus: ACM1
  port: /dev/ttyACM1
  servos:
    pan:
      id: 7
      type: feetech
      range: [-90, 90]      # Degrees from center
      default: 0            # Center position
      description: "Horizontal camera rotation"
    tilt:
      id: 8
      type: feetech
      range: [-45, 45]      # Degrees from level
      default: 0            # Level position
      description: "Vertical camera angle"

parameters:
  mode:
    type: string
    enum: [full, pan_only, tilt_only, center]
    default: full
    description: "Which servos to calibrate"
  speed:
    type: number
    minimum: 0.1
    maximum: 1.0
    default: 0.3
    description: "Movement speed during calibration"

# Uses solo-cli (solo-tech fork) for Feetech servo control
cli:
  tool: solo
  commands:
    ping: "solo robo --port /dev/ttyACM1 --ids {{id}} --ping"
    move: "solo robo --port /dev/ttyACM1 --ids {{id}} --position {{position}}"
    wiggle: "solo robo --port /dev/ttyACM1 --ids {{id}} --wiggle"
    read: "solo robo --port /dev/ttyACM1 --ids {{id}} --read"

# Calibration sequence - verbal command driven
execution:
  type: calibration_sequence
  subsystem: gantry
  cli_tool: solo

  steps:
    # Step 1: Center both servos
    - name: center_gantry
      action: move_to_position
      params:
        pan: 0
        tilt: 0
        speed: "{{speed}}"
      speak: "Centering the camera gantry"
      await_confirmation: false

    # Step 2: Test pan range
    - name: test_pan_left
      condition: "{{mode}} in ['full', 'pan_only']"
      action: move_to_position
      params:
        pan: -90
        tilt: 0
        speed: "{{speed}}"
      speak: "Panning left. Can you see the camera move?"
      await_confirmation: true

    - name: test_pan_right
      condition: "{{mode}} in ['full', 'pan_only']"
      action: move_to_position
      params:
        pan: 90
        tilt: 0
        speed: "{{speed}}"
      speak: "Panning right"
      await_confirmation: true

    - name: center_pan
      condition: "{{mode}} in ['full', 'pan_only']"
      action: move_to_position
      params:
        pan: 0
        tilt: 0
        speed: "{{speed}}"
      speak: "Centering pan"
      await_confirmation: false

    # Step 3: Test tilt range
    - name: test_tilt_up
      condition: "{{mode}} in ['full', 'tilt_only']"
      action: move_to_position
      params:
        pan: 0
        tilt: -45
        speed: "{{speed}}"
      speak: "Tilting up"
      await_confirmation: true

    - name: test_tilt_down
      condition: "{{mode}} in ['full', 'tilt_only']"
      action: move_to_position
      params:
        pan: 0
        tilt: 45
        speed: "{{speed}}"
      speak: "Tilting down"
      await_confirmation: true

    - name: center_tilt
      condition: "{{mode}} in ['full', 'tilt_only']"
      action: move_to_position
      params:
        pan: 0
        tilt: 0
        speed: "{{speed}}"
      speak: "Centering tilt. Gantry calibration complete."
      await_confirmation: false

# Dependencies
requires:
  subsystems: [gantry]
  capabilities:
    - servo_control
    - serial_port_ACM1

# Verbal triggers - human says these to start calibration
triggers:
  - pattern: "calibrate.*camera|calibrate.*gantry|test.*pan.*tilt"
    action: gantry_calibration
    params:
      mode: full

  - pattern: "center.*camera|home.*gantry"
    action: gantry_calibration
    params:
      mode: center

# Store calibration result
knowledge:
  on_complete:
    - store: "Calibrated camera gantry - pan and tilt servos confirmed working"
      salience: 40
      context:
        type: hardware_calibration
        subsystem: gantry
